Traceback (most recent call last):
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\zhangc\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import HTML
fig, ax = plt.subplots()
xdata = np.linspace(0, 2*np.pi, 100)
omega = np.linspace(1, 4, 20)
ydata = np.sin(omega[:,np.newaxis]*xdata)
hline0, = ax.plot(xdata, ydata[0], label=f'omega={omega[0]:.3f}')
hlegend = ax.legend(loc='upper right')
def hf_frame(ind0):
    hline0.set_data(xdata, ydata[ind0])
    label_i = f'{omega[ind0]:.3f}'
    # hline0.set_label(label_i) #doesn't help
    htext = hlegend.get_texts()[0]
    htext.set_text(label_i)
    return hline0,htext
ani = matplotlib.animation.FuncAnimation(fig, hf_frame, frames=len(omega), interval=200)
HTML(ani.to_jshtml())
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<module>[1;34m[0m
[0;32m     16[0m     htext[38;5;241m.[39mset_text(label_i)
[0;32m     17[0m     [38;5;28;01mreturn[39;00m hline0,htext
[1;32m---> 18[0m ani [38;5;241m=[39m [43mmatplotlib[49m[38;5;241;43m.[39;49m[43manimation[49m[38;5;241m.[39mFuncAnimation(fig, hf_frame, frames[38;5;241m=[39m[38;5;28mlen[39m(omega), interval[38;5;241m=[39m[38;5;241m200[39m)
[0;32m     19[0m HTML(ani[38;5;241m.[39mto_jshtml())

File [1;32m~\miniconda3\envs\jupyterbook\lib\site-packages\matplotlib\_api\__init__.py:222[0m, in [0;36mcaching_module_getattr.<locals>.__getattr__[1;34m(name)[0m
[0;32m    220[0m [38;5;28;01mif[39;00m name [38;5;129;01min[39;00m props:
[0;32m    221[0m     [38;5;28;01mreturn[39;00m props[name][38;5;241m.[39m[38;5;21m__get__[39m(instance)
[1;32m--> 222[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[0;32m    223[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{[39;00m[38;5;28mcls[39m[38;5;241m.[39m[38;5;18m__module__[39m[38;5;132;01m!r}[39;00m[38;5;124m has no attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m"[39m)

[1;31mAttributeError[0m: module 'matplotlib' has no attribute 'animation'
AttributeError: module 'matplotlib' has no attribute 'animation'

